### ISSUE TITLE
generate error

### ISSUE THREAD

**Issue by rmurillo21** [jantman/webhook2lambda2sqs#17]
HI - great project.  Just getting this error on generate:

I am using Roles for the server that is running the generate. Does this support roles? or is it trying get that info from the aws config in the local environment?

Thanks!

Linux ip-10-0-43-212 3.13.0-91-generic #138-Ubuntu SMP Fri Jun 24 17:00:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Python 2.7.6

webhook2lambda2sqs generate
[2016-10-07 18:27:02,632 WARNING] Writing lambda function source to: ./webhook2lambda2sqs_func.py
[2016-10-07 18:27:02,632 WARNING] Writing lambda function source zip file to: ./webhook2lambda2sqs_func.zip
[2016-10-07 18:27:02,633 WARNING] Writing terraform configuration JSON to: ./webhook2lambda2sqs.tf.json
Traceback (most recent call last):
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/bin/webhook2lambda2sqs", line 9, in <module>
    load_entry_point('webhook2lambda2sqs==0.1.0', 'console_scripts', 'webhook2lambda2sqs')()
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/src/webhook2lambda2sq/webhook2lambda2sqs/runner.py", line 351, in main
    tf_gen.generate(func_src)
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/src/webhook2lambda2sq/webhook2lambda2sqs/tf_generator.py", line 585, in generate
    fh.write(self._get_config(func_src))
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/src/webhook2lambda2sq/webhook2lambda2sqs/tf_generator.py", line 516, in _get_config
    self._set_account_info()
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/src/webhook2lambda2sq/webhook2lambda2sqs/tf_generator.py", line 282, in _set_account_info
    self.aws_account_id = conn.get_user()['User']['Arn'].split(':')[4]
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/local/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/rodm/webhook2lambda2sqs/webhook2lambda2sqs/local/lib/python2.7/site-packages/botocore/client.py", line 494, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the GetUser operation: Must specify userName when calling with non-User credentials

**Comment by rmurillo21** [comment]
That was it.  I configured the aws credentials and it worked fine.  Does not seem to work with Roles. Thanks!

**Comment by jantman** [comment]
@rmurillo21 sorry for just seeing this now.

Glad you found the project and it seems useful - you're the first person who's said they're using it.

Sorry the AWS Credential configuration wasn't more clearly documented, but I'm glad you got it working.
